### ISSUE TITLE
Custom unit specific icon does not work for out of group tracking

### ISSUE THREAD

**Issue by veteran29** [diwako/diwako_dui#105]
Units in `diwako_dui_special_track` array are not shown with their custom icon.

**Comment by diwako** [comment]
Not sure, but is this a similar case to #104? The unit either being your buddy or a squad leader? (if the unit is in a group by itself, that counts as well)

**Comment by veteran29** [comment]
Yeah the unit was in it's own group, could be nice to have an option to force the icon even if the unit is a leader.

**Comment by diwako** [comment]
I could move the priority up above SQL. So far the feature request was this to cover squad roles that are not present in dui and general in arma so far.
I do not really want to make a setting that will show the custom icon for one person and does not for another. It should be consistent for everyone. Just one thing that will be annoying is no one will know who the SQL is and who your buddy is if you disable the "Person icon" next to name.

**Comment by veteran29** [comment]
Maybe a global setting so server can force it?

**Comment by diwako** [comment]
Nah, I would prefer the prio change. if people use their own handling of icons, then they have to take things into account.

**Comment by diwako** [comment]
@veteran29 I created a new branch which changes the icon order. The DEV workshop item is also updated now. Could you check if this issue and the other one ( #104 ) will be fixed by that?

**Comment by veteran29** [comment]
Sure, I will check it in around 3-4h.

**Comment by veteran29** [comment]
Seems to be fixed by DEV branch.
