### ISSUE TITLE
ACE Pointing indicators show on disabled radar

### ISSUE THREAD

**Issue by aradiel** [diwako/diwako_dui#108]
![20190801201448_1](https://user-images.githubusercontent.com/22911153/62337496-41ed7880-b4ab-11e9-9f4d-1bd3f8f53645.jpg)

In the above screenshot you can see me pointing and the radar indicator rendering even when it's hidden because I'm alone in a group (Look around the arm, that's where I place the radar).

**Comment by Drofseh** [comment]
They also show up on the map where the radar is not visible.
