### ISSUE TITLE
Feature - Show When Group Member(s) are Talking on Radio

### ISSUE THREAD

**Issue by Quailsnap** [diwako/diwako_dui#124]
Why:
- hard to learn and recognize voices quickly. in line with "You should have seen their face before and recognize it, so you can know their name just by looking at them" this is a "You have heard their voice, you should recognize it" and a convenience present in many games

What:
- checkbox that is default on
- unit icon would be replaced by soundwave icon of a sort while they are broadcasting. unless there's some more creative way to show it (soundwave to the right of unit name would be hard to do)

How:
- ACRE XEH for whenever someone in group starts broadcasting: check if their active radio and channel are on a freq/band player can hear
- not sure about TFAR

Just a QoL feature request

**Comment by diwako** [comment]
The idea was thrown around before. However that was only in a discord server. The general consensus was pretty much "would be cool but I feel it is out of scope".

I personally would like something like that, but it comes with some technical limitations. The limitations are refresh rate.
The name lists refreshes every half a second, the compass to what ever you set it to. This means the icons will only refresh when the component itself refreshes.

I only know ACREs events for speaking, `acre_stoppedSpeaking`, `acre_startedSpeaking`, `acre_remoteStoppedSpeaking` and `acre_remoteStartedSpeaking` could be used. 
Not sure about tfar's events.

I assume a static none animated icon and only one icon for general "is speaking" would suffice?

**Comment by Quailsnap** [comment]
All would not necessarily be ideal, but definitely sufficient. I have been running a nametag script of my own design with three separate units every weekend with 10 (Folk Arps) to 30-40 (COALITION, TMTM) people each -- and this nametag script also only caches whether someone is speaking every half a second or so.

That "resolution" is a stopgap for something more detailed, but it has -- in all honesty -- been fine for nwo.

**Comment by diwako** [comment]
Seems like there is the TFAR event `OnSpeak`, which only is used locally on the player unit as far as I cna tell. This would mean extra network traffic.
