### ISSUE TITLE
request - Disable "NSEW" option

### ISSUE THREAD

**Issue by classicarma** [diwako/diwako_dui#134]
I only want to use radar, What do you think?

**Comment by diwako** [comment]
This can be achieved by having no compass.
Alternatively, you can create your own style with a mod or mission that only references the blank compasses textures.

Not sure if that is enough to go by for you.

**Comment by classicarma** [comment]
Thanks for your suggestion and I'll try it but is there any chance for adding it as a feature?😀

**Comment by diwako** [comment]
I looked into it, seems pretty easy to add. Will take a look later today and maybe make a PR if no one beats me to it.

**Comment by classicarma** [comment]
Thank you!
