### ISSUE TITLE
Feature - Choosing when to show the medic icon

### ISSUE THREAD

**Issue by Lorenz94B** [diwako/diwako_dui#137]
Hello! Can you please add a settings that allows to manually choose whether to show the medic icon on the radar if a player has the ace attribute or is of the medic classname? Let me better explain: now if a player has some sort of ace medical level, DUI automatically shows it on the radar as a medic. What I would like to do is to have the medic icon displayed only if a player is of a medic class (such as "B_medic_F" for example). This because me and my friends like to have "ace advanced diagnose" on for everyone (numeric values for heart rate and pressure), and to achieve this thing we need to set all our avatars to medic, restricting some actions such as stitching to doctors.

Thank you!

**Comment by diwako** [comment]
Done with #139
