### ISSUE TITLE
Bug - Keep losing my bearing numbers

### ISSUE THREAD

**Issue by NZF-JDWang** [diwako/diwako_dui#14]
Even with "Always show bearing" turned on there were numerous times tonight when the bearing above the compass would just disappear. Sometimes you could get it back by turning the squad radar off and on again via the keypress (thank you so much for this) but eventually it disappeared for good.

**Comment by diwako** [comment]
Thanks for the report, any way to reproduce this? I take it ACE was also loaded and you interacted a lot during the game session.

**Comment by diwako** [comment]
Fixed with cbf2d988d7790e933ef581dd8447a9f718cfbcb7
