### ISSUE TITLE
Interference between DUI Radar and dzn Rifle tripod

### ISSUE THREAD

**Issue by 10Dozen** [diwako/diwako_dui#140]
Hey, found pretty weird behaviour when using https://steamcommunity.com/sharedfiles/filedetails/?id=1720595785 with DUI radar.

When adjusting bipod (Alt+C) to remove tilt - something wrong happens:
- gun now shoots somewhere to the side
- 3rd person camera become tilted

Can't even imagine what's happening, but the reason is DUI Squad Radar mod (pbos that included into Workshop item).

![20200829180220_1](https://user-images.githubusercontent.com/9357337/91639895-7ae77c00-ea22-11ea-86f9-662730745e0c.jpg)
![20200829180213_1](https://user-images.githubusercontent.com/9357337/91639896-7c18a900-ea22-11ea-81a8-ad29d6466130.jpg)
![20200829180215_1](https://user-images.githubusercontent.com/9357337/91639897-7cb13f80-ea22-11ea-99b8-aed0cae4e2a5.jpg)

Anti-tilt is done via this piece of code running on each frame:
https://github.com/10Dozen/dzn_Rifle_Tripod/blob/9c75db0b94fedc6777abf0c80890226db09bc482/source/dzn_Rifle_Tripod/functions/fnc_affectDeployed.sqf#L22-L26

Any ideas?

**Comment by diwako** [comment]
That is... uuh.. pretty strange as DUI dopes not set any position, dir or vetctorDirAndUp to the player or the players vehicle. You sure this happens only when DUI is also loaded?

**Comment by 10Dozen** [comment]
Yeah, it really strange. But modlist is:
![image](https://user-images.githubusercontent.com/9357337/91641566-f1d64200-ea2d-11ea-8af1-0e2838a9ec4d.png)

If no Squad radar - all works as expected.

**Comment by diwako** [comment]
Is the setting "Show Names" set to false as well?

**Comment by 10Dozen** [comment]
Show names are enabled. Full settings below:
```
// DUI - Squad Radar - Indicators
force diwako_dui_indicators_crew_range_enabled = true;
diwako_dui_indicators_fov_scale = false;
diwako_dui_indicators_icon_buddy = true;
diwako_dui_indicators_icon_leader = true;
diwako_dui_indicators_icon_medic = true;
diwako_dui_indicators_range = 35;
diwako_dui_indicators_range_crew = 500;
diwako_dui_indicators_range_scale = true;
diwako_dui_indicators_show = true;
diwako_dui_indicators_size = 1;
diwako_dui_indicators_style = "diamond";

// DUI - Squad Radar - Main
diwako_dui_colors = "ace";
diwako_dui_font = "PuristaMedium";
diwako_dui_icon_style = "terry";
diwako_dui_main_hide_ui_by_default = false;
diwako_dui_main_squadBlue = [0,0,1,1];
diwako_dui_main_squadGreen = [0,1,0,1];
diwako_dui_main_squadMain = [1,1,1,1];
diwako_dui_main_squadRed = [1,0,0,1];
diwako_dui_main_squadYellow = [1,1,0,1];

// DUI - Squad Radar - Radar
diwako_dui_compass_hide_alone_group = false;
diwako_dui_compass_hide_blip_alone_group = false;
diwako_dui_compass_icon_scale = 1;
diwako_dui_compass_opacity = 1;
diwako_dui_compass_style = ["\z\diwako_dui\addons\radar\UI\compass_styles\classic\limited.paa","\z\diwako_dui\addons\radar\UI\compass_styles\classic\full.paa"];
diwako_dui_compassRange = 35;
diwako_dui_compassRefreshrate = 0;
diwako_dui_dir_showMildot = false;
diwako_dui_dir_size = 1.25;
diwako_dui_distanceWarning = 3;
diwako_dui_enable_compass = false;
diwako_dui_enable_compass_dir = 1;
diwako_dui_enable_occlusion = false;
diwako_dui_enable_occlusion_cone = 360;
diwako_dui_hudScaling = 1.46106;
diwako_dui_namelist = true;
diwako_dui_namelist_bg = 0;
diwako_dui_namelist_only_buddy_icon = false;
diwako_dui_namelist_size = 0.946325;
diwako_dui_namelist_text_shadow = 1;
diwako_dui_namelist_width = 215;
diwako_dui_radar_compassRangeCrew = 500;
diwako_dui_radar_group_by_vehicle = true;
diwako_dui_radar_icon_scale_crew = 6;
diwako_dui_radar_leadingZeroes = false;
diwako_dui_radar_namelist_hideWhenLeader = false;
diwako_dui_radar_namelist_vertical_spacing = 1.03746;
diwako_dui_radar_occlusion_fade_time = 10;
diwako_dui_radar_show_cardinal_points = true;
force diwako_dui_radar_sortType = "fireteam2";
force diwako_dui_radar_sqlFirst = false;
diwako_dui_radar_trackingColor = [0.93,0.26,0.93,1];
force diwako_dui_radar_vehicleCompassEnabled = true;
diwako_dui_reset_ui_pos = false;
diwako_dui_show_squadbar = true;
diwako_dui_use_layout_editor = false;
```

**Comment by diwako** [comment]
I could reproduce the issue, yet I have no idea why this happens in the first place.

However; I found out it happens if the DUI per framehandler is being executed before yours. So, the ID of it is lower than your pfh ID.
As soon as I stopped the radar and then restarted it while yours was still running, the per frame handler was created anew and will be executed after yours.
![image](https://user-images.githubusercontent.com/8259498/91642527-52647f80-ea2c-11ea-9406-2683d4d1c8c2.png)

The problem went away until I redeployed.

**Comment by jokoho48** [comment]
After a bit of investigation into this issue, I narrowed it down to this line https://github.com/diwako/diwako_dui/blob/master/addons/radar/functions/fnc_displayUnitOnCompass.sqf#L55
commented out the issue does not happen.
to be more precise the issue is `_player getRelDir _unit`. somehow calling this function is causing some issue internally. I will try to find a repro case and report to BI. this issue is definitely not a Mod case but an unexpected/undocumented behaviour of a script command

a Temp Fix would be to instead of using getRelDir to do
```sqf
(((getPos _player) vectorDiff (getPos _unit)) call CBA_fnc_vectDir)
```

**Comment by diwako** [comment]
Interesting find. I figured it was something similar to this but could not find the code parts in DUI.

**Comment by jokoho48** [comment]
BIF issue Open: https://feedback.bistudio.com/T153531

**Comment by jokoho48** [comment]
Update: Dedmen fixed the issue :D

**Comment by jokoho48** [comment]
2.06 release and fixed this issue
