### ISSUE TITLE
Bug - Indicators colors don't update when the compass is hidden

### ISSUE THREAD

**Issue by synixebrett** [diwako/diwako_dui#143]
For some OPs we disable the compass, when we do the indicator colors do not update to match the team color. They sit on whatever the last color was when the compass was visible.

**Comment by diwako** [comment]
I take it `diwako_dui_enable_compass` and `diwako_dui_namelistdiwako_dui_namelist` are set to `false`. If that is the case then yes, the compass cache loop will not not update the colors anymore. Indicators are querying the color from the compass component.

**Comment by synixebrett** [comment]
Yeah, the colors code will likely need to be pulled into the main component

**Comment by diwako** [comment]
Yeah, I think so, too. It is due to move that part from radar to main.

**Comment by diwako** [comment]
Fix is now available on DEV workshop item!
https://steamcommunity.com/sharedfiles/filedetails/?id=1617125729
