### ISSUE TITLE
Request: Radar Size options

### ISSUE THREAD

**Issue by ShoppyCodes** [diwako/diwako_dui#155]
Hello

Would be great to be have a slider for radar size, for me it seems a little small especially since I'm so used to using ShacktacUI which has a slightly larger radar.

**Comment by diwako** [comment]
Hey,
DUI has a setting for this, check out this one you can find in the CBA settings window
![image](https://user-images.githubusercontent.com/8259498/95783341-ec794200-0cd1-11eb-95de-017eb2b40b69.png)

**Comment by ShoppyCodes** [comment]
Oops! You are right. Apologies, I am stupid. In my menu it has "Show Vanilla Squad Bar" toggle box next to it (no ACE loaded) and so I thought it was in relation to the vanilla squad bar and not the radar.  My bad! Thanks!

**Comment by diwako** [comment]
No problem, feel free to reopen the issue if that did not fully help you.
