### ISSUE TITLE
Chinese Simplified and Chinese Traditional Translation

### ISSUE THREAD

**Issue by YRUSoPractised** [diwako/diwako_dui#159]
I want to help with adding Chinese Simplified and Chinese Traditional translation, but I am really new to Github and have no idea how to make a pull request.

So here are the XML files.

https://drive.google.com/drive/folders/1ZW2qOrbhN_BZgXATaNq9VDX4b9zcKZOI?usp=sharing

Sorry for added my translation directly under the lines of English. It is only for my convenience of translation.

**Comment by diwako** [comment]
Hey, thanks for the translations! I will look over them and then add them to this repo. Git (and GitHub ) is a bit hard to get into if one does not have a software dev background, so this way is fine as well.

**Comment by diwako** [comment]
May I ask your username, so I can add you to the authors file?

**Comment by YRUSoPractised** [comment]
YRUSoPractised

Thank you
