### ISSUE TITLE
members are recieveing the following error

### ISSUE THREAD

**Issue by YonVclaw** [diwako/diwako_dui#164]
Folks are recieving the following error , a few 100k times, enough that its cuaseing other issues 

```
16:58:20 File z\diwako_dui\addons\radar\functions\fnc_getIcon.sqf..., line 82
16:58:20 Error in expression <e;
};
private _delete = false;
{
if (_x select 0 > CBA_missionTime) exitWith {};>
16:58:20   Error position: <select 0 > CBA_missionTime) exitWith {};>
16:58:20   Error select: Type Object, expected Array,String,Config entry
16:58:20 Error in expression <e;
};
```

the mod list for reference

> CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
> -- | -- | --
> ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
> SPS-Weapons | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1069692316
> SPS Equipment | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1187306764
> Enhanced Movement | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
> KAT - Advanced Medical REWRITE | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2020940806
> Task Force Arrowhead Radio (BETA!!!) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=894678801
> SPS Texture Pack 2 for SPS Equipment and Weapons | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1427701071
> SPS Textures Pack1 for SPS Equipment and Weapons | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1389664355
> Special Stealth Uniforms [SSU] | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2122147403
> SSU Protective Gear Upgrade | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2122144692
> Simplex Support Services | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1850026051
> Breaching Charge | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1314910827
> MX Series Retexture | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1388025252
> Commandeer AI (Rankless) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1510111798
> dzn Extended Jamming | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1379304937
> Simple MapTools | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2013446344
> Enhanced Movement Rework | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2034363662
> DUI - Squad Radar | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1638341685
> BackpackOnChest | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=820924072
> DPSO Custom v4 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1675214293
> WY_Snow_Winter_Effects_and_Retexture_Pack | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=819154831
> White MX rifles (winter camo!) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=369348419
> Hellanmaa | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1291778160
> CUP Terrains - Core | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
> RulingCommander's Winter NATO | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1664288935
> 2035: Russian Armed Forces | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=543460260
> ALiVE | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=620260972
> Advanced Rappelling - Reworked | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2073987581

**Comment by diwako** [comment]
Interestingly enough, the code snippet that is failing is not even in DUI at all.
`if (_x select 0 > CBA_missionTime) exitWith {}`

As DUI is relying heavily on CBA, it might be an issue there.
As expected that code snippet is in CBA and also in a component that is heavily used in DUI, the per frame handler
https://github.com/CBATeam/CBA_A3/blob/855b523aae48b70c6d076c185dcda4c64c9f1290/addons/common/init_perFrameHandler.sqf#L49

This means something is breaking CBA...

Some questions:
What kind of missions are you playing, is Invade and Annex one of them by any chance?
Can you reproduce the issue reliably?
If the issue is reproduced and currently happening, please dump the contents of this variable `cba_common_waitAndExecArray`, put it into a pastebin and post it here (just exec it in the debug console)

It also helps out thinning out the mods you are using one by one and see if the issue disapears.

**Comment by YonVclaw** [comment]
That's what i'm doing now, below is the git repo to the mission, we started to have issues at the last ace update,
So may errors that it would cause desync issues.
https://github.com/DPSO/Missions/tree/main/bearviper5.hellanmaaw

**Comment by YonVclaw** [comment]
Is the mod required server side? Or is it just client?

**Comment by diwako** [comment]
DUI is not required server side, it has some server side components and CBA setttings, but it is not really needed for it to work.

**Comment by diwako** [comment]
Another thing, also try out an empty mission and see if it happens there. The mission you posted has a lot going on.

**Comment by YonVclaw** [comment]
And just to make troubleshooting fun, I can only reproduce the error with 4 more more players on the server, no errors, until the 4th play joins then it takes a few minutes, then ever player is flooded with the error,

**Comment by diwako** [comment]
if that is the case start with the bare minimum, DUI and CBA (Ace can also be loaded). Means you can eliminate the issue within DUI itself.

**Comment by YonVclaw** [comment]
Well, without changing anything, we can no longer produce the error,

**Comment by Grezvany13** [comment]
Seems to be the same as #166 (which can be reproduced, and with reason why)
