### ISSUE TITLE
Error when `ACE_isEOD` is set with a number instead of boolean

### ISSUE THREAD

**Issue by Grezvany13** [diwako/diwako_dui#166]
**Mods (complete and add to the following information):**

- **Arma 3:** `2.00 stable`
- **CBA:** `3.15.2`
- **DUI:** `1.8.0`
- **ACE:** `3.13.5`
  _Make sure to reproduce the issue with only CBA and DUI on a newly created mission!_

**Description:**
When a player has the variable `ACE_isEOD` set with a number as value (instead of boolean), DUI will generate the following error:
```
Error in expression <(_unit getVariable ["ACE_isEOD", false] || {_unit getUnitTrait "explosiveSpecial>
   Error position: <|| {_unit getUnitTrait "explosiveSpecial>
   Error Generic error in expression
File z\diwako_dui\addons\radar\functions\fnc_getIcon.sqf..., line 82
```
and causes CBA to get stuck in a loop causing additional errors (and filling the RPT file).
Additionally will it break other functions which use CBA (including ACE).

**Steps to reproduce:**
- Create new mission in 3den
- Place down 2 units in seperate groups
- Put the following code in the init field of the player unit:
```
this setVariable ["ACE_isEOD", 1, true];
```
- Play the scenario (SP or MP)
- Try to join the group of the second unit

**Expected behavior:**
Since ACE allows both booleans and numbers to be used in `ACE_isEOD` (see: [fnc_isEOD.sqf](https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/common/functions/fnc_isEOD.sqf#L23)), I expect that DUI also allows both.
`ACE_medical_medicClass` and `ACE_IsEngineer` are both handled as numbers (and not booleans), it makes sense to at least be consistent for all three variables.

**Where did the issue occur?**
First occured on dedicated server with several mods, tested in singleplayer with only CBA, ACE and DUI enabled.

**Additional context:**
N/A

**Log Files:**
N/A error is described in description

**Screenshots:**
N/A

**Comment by diwako** [comment]
Hey thanks for the report. Will take a look into fixing this. In the meantime, the current work around is setting the variable to a boolean.

The other two variables should be already handled, `ACE_medical_medicClass` is infact a number only, boolean is not allowed here, it is used for medic and doctor differences.

**Comment by Grezvany13** [comment]
It's a minor issue and we fixed it already on our side, and afaik do most mods set a boolean anyway (like 3den Enhanced and ZEN).

As for medic and engineer, those are indeed always numbers (from ACE), so nothing needs to be changed in those cases.
