### ISSUE TITLE
Feature - Add ability to hide Compass like namelist when alone in a group

### ISSUE THREAD

**Issue by diwako** [diwako/diwako_dui#17]
Title

**Comment by Drofseh** [comment]
I was thinking about this the other day.
It might be nice to either totally hide the compass, or to only hide the player's icon on the compass.

**Comment by diwako** [comment]
@Drofseh  TBH, just hiding your own blip is probably not enough. As far as I understood the sentiment of this request, it was like "the whole thing is not useful if you are alone". Personally disagree, but hey more options for more people!

**Comment by Drofseh** [comment]
Yah, I would want to keep the compass the whole time but have my blip be hidden if I am alone.

**Comment by diwako** [comment]
Committed with 2835c1b8279e72556d9d1fcc842a1c27289fb8ed

@Drofseh your suggestion is in there as well ;)
