### ISSUE TITLE
FEATURE: Add setting for prioritising Medic/Engineer/EOD icons

### ISSUE THREAD

**Issue by johnb432** [diwako/diwako_dui#189]
**Is your enhancement related to a problem?**

The unit I'm in sets everyone to engineer status. Therefore, we can't see who has an MG or launchers, which we could before the update on the 13.4.2021. (Basically, we have the reverse problem of #163).

**Solution you'd like:**

Add a setting that allows you to switch between the new priority system for icons (the one introduced in #180) and the old one (the one prior to #180).

**Alternatives:**

Implement the original suggestion of #163:
> I would like to suggest an Addon Settings Option where the individual user can choose what they would like to prioritise. Weaponary or Skill-Traits, ...

**Comment by diwako** [comment]
Closing due to merged pr
