### ISSUE TITLE
LIS checks inside fast moving vehicles behave unexpectedly due to simulation time scope nature of `positionCameraToWorld`

### ISSUE THREAD

**Issue by derbismarck** [diwako/diwako_dui#194]
**Description:**

The new LIS checks use `positionCameraToWorld` in order to perform a `lineIntersectsSurfaces` from the player camera position out from the center of the screen. Unfortunately, `positionCameraToWorld` does _not_ return position in render time, so when in a quickly moving vehicle its usage is unreliable. You see this manifest when inside a fast vehicle, where the nametags appear to display when looking in an area _in front of_ the target unit with respect to the velocity of the parent vehicle. For example, when you look at your co-pilot in a littlebird while in fast forward flight (looking off to the right), you see their nametag when looking at relative bearing 045, out into space in front of the co-pilot. This is because the simulation position is almost always behind the render position, and `positionCameraToWorld` is simply grabbing the render position of the camera, so lags behind. If you point at relative bearing 090 (directly at your copilot), you don't get their nametag, because the line trace in physical space misses them completely.

**Steps to reproduce:**

- Fly quickly in an aircraft
- Note that nametags are displayed in an offset fashion when looking _ahead_ of the intended target, with respect to the direction of travel of the parent aircraft

(_exact_ repro steps)
1. Get in a helicopter
2. Bring it to a hover
3. Look directly at a crew member
4. Translate into horizontal flight, while continuing to look directly at the same crew member
5. Note that the nametag disappears once you move fast enough, and will reappear if you slow back down

**Expected behavior:**

- Fly quickly in an aircraft
- Nametags are displayed exactly as they are when the air vehicle is stationary. No offsetting WRT the direction of aircraft flight.

**Additional context:**

I've been trying to find a solution to this, but as far as I know there isn't any way to get an exact camera position in render time... so yeah. I did find one possible way, but it's icky and doesn't give you _exactly_ the render pos. It's at least a little better than without the correction though. That's in the "Possible Fix" section at the bottom.

Additional information re. render time vs simulation time: https://community.bistudio.com/wiki/Simulation_vs_Render_Time_Scope

**Showcase of the issue:**

https://youtu.be/W-LMOqx4HoY (HD should process soon™)

Concept for the visualization there is that red shows you the start of the LIS check, blue is the middle, and green is the end. This just helps visualize which direction the line is offset in.
```sqf
onEachFrame {
    drawLine3D [positionCameraToWorld [0,0,0], positionCameraToWorld [0,0,1], [1,0,0,1]];
    drawLine3D [positionCameraToWorld [0,0,1], positionCameraToWorld [0,0,2], [0,0,1,1]];
    drawLine3D [positionCameraToWorld [0,0,2], positionCameraToWorld [0,0,1000], [0,1,0,1]];
};
```

**Possible Fix:**

https://youtu.be/oZ0mkZPfCrk (video is with the DUI code LIS check overridden with the code below _labeled B_)

Basic idea here is that we try to fudge the actual render position of the camera by assuming it's exactly one frame-ish ahead of the current one. If the framerate is changing rapidly this isn't so accurate, and if the vehicle is accelerating that can also throw things off, _and_ in general it's a bit flickery, so I'm not really satisfied with it. However, it appears to be the best that can be done at the moment with the current commands available to us. I'm sure there are ways to clean this up to make it work more nicely, but this is just a napkin-scribble idea at present.

Code A (ran during the video for the sake of attempting to visualize the LIS check):
```sqf
onEachFrame {
    private _fudge = ((velocity (vehicle ace_player)) vectorMultiply diag_deltaTime);
    private _camPos = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,0])) vectorAdd _fudge);
    private _pos1 = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,1])) vectorAdd _fudge);
    private _pos2 = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,2])) vectorAdd _fudge);
    private _endPos = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,1000])) vectorAdd _fudge);
    drawLine3D [_camPos, _pos1, [1,0,0,1]];
    drawLine3D [_pos1, _pos2, [0,0,1,1]];
    drawLine3D [_pos2, _endPos, [0,1,0,1]];
};
```

Code B (changes to the LIS usage in `diwako_dui_nametags_fnc_onDraw`):
```sqf
if (GVAR(useLIS)) then {
    private _fudge = ((velocity (vehicle ace_player)) vectorMultiply diag_deltaTime);
    private _camPos = (AGLtoASL (positionCameraToWorld [0,0,0])) vectorAdd _fudge;
    private _endPos = (AGLtoASL (positionCameraToWorld [0,0,GVAR(renderDistance) + 1])) vectorAdd _fudge;
    private _lis = lineIntersectsSurfaces [
        _camPos,
        _endPos,
        _player,
        objNull,
        true,
        -1,
        "FIRE"
    ];
    . . .
```

**Comment by jokoho48** [comment]
Hey, thanks for the detailed Report.
back when I added that in I also noticed this issue but did not found a solution around it. but decided that it was better than nothing. 😄 
would you like to open the PR to fix it? or should I do it?

**Comment by derbismarck** [comment]
Found a better solution, although it's still not 100% perfect. ACRE uses this to get the listener position:

```sqf
acre_player modelToWorldVisualWorld (acre_player selectionPosition "pilot");
```

Using that along with `getCameraViewDirection`, the "it's not perfect" aspect is that it doesn't obey TrackIR X, Y, Z position. Rotation all works as expected, but the origin position of the LIS check doesn't move to the left if you were to hang your head out of the left side of a helicopter, for example. TrackIR's 6DoF is somewhat of an edge case, so I think this is fine given the limitations we've got going here. I don't really like the fudgy method I mentioned above, if you disable TrackIR and alt-look around the helicopter, the maximal error between the exact camera position (as given by the ACRE method) vs. the one given by the fudged method can easily be greater than ~10cm.

This code spits out a system chat every time the error is larger than 10cm. It happens fairly frequently at a smooth 60FPS, and if I crank my graphics settings up to purposefully degrade performance it gets pretty bad. Given how the game usually performs in an MP context, I don't think it's a good idea to rely on the fudge method.
```sqf
onEachFrame {
    private _fudge = ((velocity (vehicle ace_player)) vectorMultiply diag_deltaTime);
    private _camPos = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,0])) vectorAdd _fudge);
    private _pos1 = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,1])) vectorAdd _fudge);
    private _pos2 = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,2])) vectorAdd _fudge);
    private _endPos = ASLtoAGL ((AGLtoASL (positionCameraToWorld [0,0,1000])) vectorAdd _fudge);
    drawLine3D [_camPos, _pos1, [1,0,0,1]];
    drawLine3D [_pos1, _pos2, [0,0,1,1]];
    drawLine3D [_pos2, _endPos, [0,1,0,1]];


    private _camPosExact = ace_player modelToWorldVisualWorld (ace_player selectionPosition "pilot");
    private _error = _camPos distance (ASLtoAGL _camPosExact);
    if (_error > 0.1) then {systemChat str _error};
};
```

I'll submit a pull request that utilized the ACRE listener position code in a little while.
