### ISSUE TITLE
DUI Radar unable to move with Layout Editor

### ISSUE THREAD

**Issue by whitfieldl** [diwako/diwako_dui#196]
**Description:**

When repositioning DUI Radar through Layout Editor. The DUI Radar will not shift upon complete game restart. 

**Steps to reproduce:**

- Place down Units in Editor
- Preview
- Open: Configure -> Game -> Layout
- Move DUI Radar to bottom left of the screen
- Hit "Okay"
- Play

**Expected behavior:**

DUI Radar & Nametags will be moved towards the bottom left of the screen

**Additional context:**

Attempted to follow the steps from this forum post - https://forums.bohemia.net/forums/topic/221597-dui-squad-radar/?page=2&tab=comments#comment-3338074 - to no avail.

**Comment by diwako** [comment]
Which DUI and CBA version are you using?

Have you check the checkbox in CBA settings inside the Radar component named `Use A3 Layout Editor Position` to use the layout editor values instead of the generated ones?

**Comment by diwako** [comment]
This ticket is now 2 weeks in active, if the issue persists feel free to reopen it.
