### ISSUE TITLE
Help/Bug: Icons near name list are pixelated/bad quality (unlike the high-quality ones in the steam workshop screenshots)

### ISSUE THREAD

**Issue by ShoppyCodes** [diwako/diwako_dui#198]
**Mods (complete and add to the following information):**
DUI + CBA only

- **Arma 3:** ` 2.04.147719 stable` [e.g. 1.00 stable, rc, dev, profiling]
- **CBA:** `v3.15.3` [e.g. 3.0.0 stable]
- **DUI:** `1.9.2` [eg. 1.5.0 stable]
  _Make sure to reproduce the issue with only CBA and DUI on a newly created mission!_

**Description:**

Icons near namelist are bad quality/pixelated on mine, but seem fine on everyone elses?

**Steps to reproduce:**

1. Load DUI + CBA mods
2. Launch game
3. Go into editor and make a squad
4. Enter game to see DUI HUD

**Expected behavior:**

Like within the screenshots on the steam workshop page, high-quality icons. 

**Where did the issue occur?**

- Everywhere

**Additional context:**

- I am using a standard 1080p screen.
- Even with default settings, the icons are still bad quality/pixelated 

Mod settings export
// CBA UI
cba_diagnostic_ConsoleIndentType = -1;
cba_ui_notifyLifetime = 4;
cba_ui_StorePasswords = 1;

// CBA Weapons
cba_disposable_dropUsedLauncher = 2;
force cba_disposable_replaceDisposableLauncher = true;
cba_events_repetitionMode = 1;
cba_optics_usePipOptics = false;

// Community Base Addons - Network
force cba_network_loadoutValidation = 1;

// DUI - Squad Radar - Indicators
force diwako_dui_indicators_crew_range_enabled = true;
diwako_dui_indicators_fov_scale = false;
diwako_dui_indicators_icon_buddy = true;
diwako_dui_indicators_icon_leader = true;
diwako_dui_indicators_icon_medic = true;
diwako_dui_indicators_range = 100;
diwako_dui_indicators_range_crew = 300;
diwako_dui_indicators_range_scale = false;
diwako_dui_indicators_show = true;
diwako_dui_indicators_size = 1;
diwako_dui_indicators_style = "standard";

// DUI - Squad Radar - Main
diwako_dui_colors = "ace";
diwako_dui_font = "PuristaSemibold";
diwako_dui_icon_style = "standard";
diwako_dui_main_hide_dialog = true;
diwako_dui_main_hide_ui_by_default = false;
diwako_dui_main_squadBlue = [0,0,1,1];
diwako_dui_main_squadGreen = [0,1,0,1];
diwako_dui_main_squadMain = [1,1,1,1];
diwako_dui_main_squadRed = [1,0,0,1];
diwako_dui_main_squadYellow = [1,1,0,1];
diwako_dui_main_trackingColor = [0.93,0.26,0.93,1];
diwako_dui_reset_ui_pos = false;

// DUI - Squad Radar - Nametags
diwako_dui_nametags_deadColor = [0.2,0.2,0.2,1];
diwako_dui_nametags_deadRenderDistance = 3.5;
diwako_dui_nametags_drawRank = false;
diwako_dui_nametags_enabled = true;
diwako_dui_nametags_enableFOVBoost = true;
diwako_dui_nametags_enableOcclusion = true;
diwako_dui_nametags_fadeInTime = 0.05;
diwako_dui_nametags_fadeOutTime = 0.5;
diwako_dui_nametags_fontGroup = "PuristaLight";
diwako_dui_nametags_fontGroupNameSize = 8;
diwako_dui_nametags_fontName = "PuristaMedium";
diwako_dui_nametags_fontNameSize = 10;
diwako_dui_nametags_groupColor = [1,1,1,1];
diwako_dui_nametags_groupFontShadow = 2;
diwako_dui_nametags_groupNameOtherGroupColor = [0.6,0.85,0.6,1];
diwako_dui_nametags_nameFontShadow = 2;
diwako_dui_nametags_nameOtherGroupColor = [0.2,1,0,1];
diwako_dui_nametags_renderDistance = 40;
diwako_dui_nametags_showUnconAsDead = true;
diwako_dui_nametags_useLIS = true;
diwako_dui_nametags_useSideIsFriendly = true;

// DUI - Squad Radar - Radar
diwako_dui_compass_hide_alone_group = false;
diwako_dui_compass_hide_blip_alone_group = true;
diwako_dui_compass_icon_scale = 1.1;
diwako_dui_compass_opacity = 0.8;
diwako_dui_compass_style = ["\z\diwako_dui\addons\radar\UI\compass_styles\classic\limited.paa","\z\diwako_dui\addons\radar\UI\compass_styles\classic\full.paa"];
diwako_dui_compassRange = 35;
diwako_dui_compassRefreshrate = 0;
diwako_dui_dir_showMildot = false;
diwako_dui_dir_size = 1;
diwako_dui_distanceWarning = 3;
diwako_dui_enable_compass = true;
diwako_dui_enable_compass_dir = 2;
diwako_dui_enable_occlusion = false;
diwako_dui_enable_occlusion_cone = 360;
diwako_dui_hudScaling = 1.1;
diwako_dui_namelist = true;
diwako_dui_namelist_bg = 0;
diwako_dui_namelist_only_buddy_icon = false;
diwako_dui_namelist_size = 0.9;
diwako_dui_namelist_text_shadow = 2;
diwako_dui_namelist_width = 180;
diwako_dui_radar_compassRangeCrew = 500;
diwako_dui_radar_dir_padding = 8;
diwako_dui_radar_dir_shadow = 2;
diwako_dui_radar_group_by_vehicle = true;
diwako_dui_radar_icon_opacity = 1;
diwako_dui_radar_icon_opacity_no_player = true;
force diwako_dui_radar_icon_priority_setting = 1;
diwako_dui_radar_icon_scale_crew = 6;
diwako_dui_radar_leadingZeroes = true;
diwako_dui_radar_namelist_hideWhenLeader = false;
diwako_dui_radar_namelist_vertical_spacing = 1;
diwako_dui_radar_occlusion_fade_in_time = 1;
diwako_dui_radar_occlusion_fade_time = 10;
diwako_dui_radar_show_cardinal_points = true;
force diwako_dui_radar_sortType = "fireteam";
force diwako_dui_radar_sqlFirst = true;
force diwako_dui_radar_vehicleCompassEnabled = true;
diwako_dui_show_squadbar = true;
diwako_dui_use_layout_editor = false;

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**
![image](https://user-images.githubusercontent.com/26325324/122216648-88340100-cea4-11eb-95aa-8546b6fb53cd.png)

**Comment by diwako** [comment]
That is sadly a scaling filtering issue in arma, highlighted further with the shadow outline . It happens as it needs to scale down the icons. There is nothing i can do other than recommend using the drop shadow option.

In general, arma text renderer is terrible with scaling, mostly because text is not vector graphic, same goes for icons. It is possible to make multiple icons in many scales to combat that, but in the end there will be still artefacts, thus it is not feasible.

**Comment by ShoppyCodes** [comment]
Thanks for the quick response!

I'm curious, are the text symbols handled differently to the radar symbols? The radar ones seem to scale properly

**Comment by ShoppyCodes** [comment]
Drop-shadow helps quite a bit too, thanks!

**Comment by diwako** [comment]
In arma as mentioned, text are just rendered images, but the main difference is text as multiple sizes, so if the displayed text is small it uses a smaller sample size, thus it does not start looking as weird.

**Comment by ShoppyCodes** [comment]
I see, cool thanks for the info.
