### ISSUE TITLE
Error in mod.cpp

### ISSUE THREAD

**Issue by formtapez** [diwako/diwako_dui#201]
Hi, in `mod.cpp` of your releases, the lines
`hidePicture = "false";`
`hideName = "false";`
are wrong. Please replace them by
`hidePicture = 0;`
`hideName = 0;`

Otherwise, the server-log shows many many errors like: (shorted)
`Global namespace not passed during: false`
`14:39:43 Error in expression <false>`
`14:39:43   Error position: <false>`
`14:39:43   Error Local variable in global space`
`...`

**Comment by diwako** [comment]
I wondered where that error came from. Will be fixed in next version

**Comment by diwako** [comment]
Fixed with 1.9.3
