### ISSUE TITLE
Option to remove vehicle icons from namelist

### ISSUE THREAD

**Issue by MrFleff** [diwako/diwako_dui#209]
**Is your enhancement related to a problem?**

It's a problem of immersion in our group.
Currently players of the same group with the name list active can see others in vehicle driver seats, gunner seats, etc.
The problem in my group being that you gain a bit to much awareness knowing the status on comrades kilometers away that you otherwise wouldn't.

**Solution you'd like:**

An add-on option to select between showing players in vehicles or not possibly similar to the ACRE/TFAR option to show people speaking.

**Alternatives you've considered:**

If easier, an option to just disable the player icons in the name list entirely would achieve the same thing.

**Additional context:**

No additional context beyond our group having immersion breaking moments because of this. For example when ex filling from an objective we've had people unaccounted for and the namelist has been used to see if individuals have made it to the extract vehicle or not.

**Comment by mrschick** [comment]
I fully agree with the unrealistic SA given by the "in vehicle" icons, has been a minor gripe of mine for some time.

The only issue is that inside a vehicle, ACE Nametags are not always visible and moving around to look at everyone is more restrictive than IRL.
It would be better imo if that new setting had multiple options instead, like:
- Show
- Only show on players in the same or nearby vehicle
- Don't show

I can look into implementing that in the next few days, depending on the whether changing an existing setting's type like that is acceptable or something else is preferable.

**Comment by diwako** [comment]
The change in settings type is fine. people just need to redo that one setting.
