### ISSUE TITLE
Game Stuck at loading screen with version 1.10.0 Loaded

### ISSUE THREAD

**Issue by Haitham4** [diwako/diwako_dui#217]
**Mods (complete and add to the following information):**

- **Arma 3:** 2.14 [Latest]
- **CBA: v3.16.1.231025
- **DUI: 1.10.0 stable
  _Make sure to reproduce the issue with only CBA and DUI on a newly created mission!_

**Description:**

since the latest update yesterday [1.10.0], I am unable to load a saved game. basically the game hangs on the loading screen. 

I resolved the issue by copying the content of the previous version [1.9.3] into the folder of current DUI mod effectively reverting to the older version.  that worked. 

Issue happens with CBA and DUI only as well. 

**Steps to reproduce:**

- load game with DUI
- open Eden editor and place a soldier 
- Just save game and try to reload it

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer)

**Additional context:**

**Log Files:**

**Screenshots:**

**Comment by diwako** [comment]
Thanks I will be looking into that tomorrow, could you upload an RPT in the mean time?

**Comment by Haitham4** [comment]
> I will be looking into that tomorrow

Thank you.

> could you upload an RPT in the mean time?

but these are generated when the game crashes no ? in this case the game just hangs on a loading screen and I force close it.
nonetheless this is the last RPT file I see, before I changed the mod files manually. not sure if this is what you're looking for

[rpt.zip](https://github.com/diwako/diwako_dui/files/13769521/rpt.zip)

**Comment by jokoho48** [comment]
> > I will be looking into that tomorrow
> 
> Thank you.
> 
> > could you upload an RPT in the mean time?
> 
> but these are generated when the game crashes no ? in this case the game just hangs on a loading screen and I force close it. nonetheless this is the last RPT file I see, before I changed the mod files manually. not sure if this is what you're looking for
> 
> [rpt.zip](https://github.com/diwako/diwako_dui/files/13769521/rpt.zip)

the RPT says you dont load a single mod. so also not DUI nor CBA so you should first try loading the mods and than send the newly generated RPT

**Comment by diwako** [comment]
Tried to reproduce just now.

- Started game with CBA, DUI and ACE loaded.
- Went into editor
- placed unit
- preview game
- save
- restart

Loads as expected

**Comment by diwako** [comment]
Just checked in the old man campaign as well.

Made a manual save
Loaded the save

Works as intended.

**Comment by diwako** [comment]
Please check with latest DUI version, this might have fixed the issue

**Comment by Haitham4** [comment]
> Please check with latest DUI version, this might have fixed the issue

Thank you. currently I don't have access to my PC for a few days, but I will check and update the thread here once back

**Comment by Haitham4** [comment]
seems like the issue no longer occurs. I formatted my computer so it might've been something else
