### ISSUE TITLE
Weird TFAR Beta incompatibility

### ISSUE THREAD

**Issue by johnb432** [diwako/diwako_dui#218]
**Mods (complete and add to the following information):**

- **Arma 3:** `2.14` latest stable and profiling
- **CBA:** `3.16.1` stable
- **DUI:** `1.10.0` stable
  _Make sure to reproduce the issue with only CBA and DUI on a newly created mission!_

**Description:**

When having CBA, ACE, DUI and TFAR Beta loaded and hosting a mission from the editor in MP, it doesn't apply the font and size to the radar on mission start.

**Steps to reproduce:**

- Make a mission.
- Host from editor.
- Start mission.
- Observe that font and size have not been applied.

**Expected behavior:**

**Where did the issue occur?**

- Editor (Multiplayer)

**Additional context:**

I reproduced the unexpected behaviour on another PC, with my unit's modset (which contains TFAR Beta, PC is running latest profiling).

---

I built the mod locally with HEMTT 1.10.2. I added some modifications from the start, such as delaying the executing of `FUNC(cacheLoop)` in `radar`, but that made it worse. I had some luck with:
```sqf
// start the loop
GVAR(setCompass) = false;
[] call FUNC(cacheLoop);
GVAR(setCompass) = true;
```
but it means that it takes 0.5s to apply the settings, which isn't ideal.
However, when I built the mod without any modifications of my own, it worked.

I've made sure that it isn't a corrupted mod. I compared the contents of the `radar` PBOs (steam workshop vs locally built) and `fnc_cacheLoop.sqf` are the same, however the `fnc_cacheLoop.sqfc` files differ. I removed the `fnc_cacheLoop.sqfc` file from the workshop version but it didn't make a difference.

**Log Files:**
- Nothing of relevance in the RPT, I hope you don't mind me not uploading it.

**Screenshots:**

**Comment by diwako** [comment]
Does this also happen when you just use `hemtt launch` with TFAR added as mod?

**Comment by diwako** [comment]
Another question, are you on the profiling branch and running the performance binary?

**Comment by johnb432** [comment]
> Does this also happen when you just use `hemtt launch` with TFAR added as mod?

No. Since I presume it's identical to `hemtt build` and manually launching, it's a good thing that they both produce the same result.

> Another question, are you on the profiling branch and running the performance binary?

I think so, but I'll describe what I did, just to be sure: I chose the "profiling - performance profiling build" in the steam betas menu. I'm not running the companion mod https://steamcommunity.com/sharedfiles/filedetails/?id=2419451036.

I reverted to the stable branch to ensure it wasn't that causing the problem. I ran the `hemtt launch` test on the stable branch.

**Comment by diwako** [comment]
I reproduced the issue with wrong sizes and such. That issue happens in all build steps from hemtt. The only time it does not happen is when filepatching is involved. Which leads me to that it is an SQFC issue.

**Comment by diwako** [comment]
as you wrote, running `"diwako_dui_radar_refreshUI" call CBA_fnc_localEvent` will fix it, so it is really damn strange what is going on.

**Comment by johnb432** [comment]
> [diwako_dui-1.10.0.1.zip](https://github.com/diwako/diwako_dui/files/13798596/diwako_dui-1.10.0.1.zip) could you try this version? Code base is virtually the same, just no SQFC added. In my local tests it works, but I kind of want confirmation first.

It works.

**Comment by diwako** [comment]
I will then release a fixed version without SQFC and then wonder why it does not work and who to annoy to get that fixed.

**Comment by johnb432** [comment]
> I will then release a fixed version without SQFC and then wonder why it does not work and who to annoy to get that fixed.

Hold that, something is still being weird, give me a few.

**Comment by johnb432** [comment]
> Hold that, something is still being weird, give me a few.

It works when you are alone in MP. However, I had a client join me and it reverted the size and font.
I'm going to investigate further and give a better report on that.

**Comment by diwako** [comment]
Which is really weird, still. Comparing the changes between last version and current version. The changes in the SQF files themselves are minimal

https://github.com/diwako/diwako_dui/compare/1.9.3...1.10.0

**Comment by johnb432** [comment]
> It works when you are alone in MP. However, I had a client join me and it reverted the size and font. I'm going to investigate further and give a better report on that.

The client had the workshop version of DUI installed.
I don't know how, but apparently that client was able to change the font and size on server's end... It didn't change the CBA settings as far as I could tell. What's worse is that both the client and the server have the exact same font setting, so I have no idea why it would revert.
With the server and client both having the non-SQF-compiled version, it works.

> Which is really weird, still. Comparing the changes between last version and current version. The changes in the SQF files themselves are minimal
> 
> [1.9.3...1.10.0](https://github.com/diwako/diwako_dui/compare/1.9.3...1.10.0)

My guess is the version of HEMTT you built with might have a problematic SQF compiler. https://github.com/BrettMayson/HEMTT/releases/tag/v1.11.0-rc3 is still rather experimental after all.

Either way, I'm confused as fuck.

**Comment by diwako** [comment]
Last version before updating hemmt use a middle step to run the arma script compiler directly before packaging.

Basically the largest change was updating hemtt.

**Comment by diwako** [comment]
@johnb432 Could you try this one? SQFC is included and I found no issue in testing so far.

Only thing what i did was to clear `%localappdata%/hemtt` before rebuilding
[diwako_dui-1.10.1.0.zip](https://github.com/diwako/diwako_dui/files/13799017/diwako_dui-1.10.1.0.zip)

**Comment by johnb432** [comment]
> @johnb432 Could you try this one? SQFC is included and I found no issue in testing so far.
> 
> Only thing what i did was to clear `%localappdata%/hemtt` before rebuilding [diwako_dui-1.10.1.0.zip](https://github.com/diwako/diwako_dui/files/13799017/diwako_dui-1.10.1.0.zip)

Seems to work.
