### ISSUE TITLE
Compass/Bearing reset position when loading saved game

### ISSUE THREAD

**Issue by aradiel** [diwako/diwako_dui#29]
When playing singleplayer and loading a saved game, the compass and bearing indicators will return to their default positions, despite of what the UI editor shows:
![107410_20190206193044_1](https://user-images.githubusercontent.com/22911153/52375351-978a2080-2a46-11e9-9f28-11383b5792bf.png)
![107410_20190206193109_1](https://user-images.githubusercontent.com/22911153/52375352-9822b700-2a46-11e9-842e-e9caf45cec31.png)
In the screenshots above you can see the HUD was supposed to be in the lower left corner, but only the names were moved.

**Comment by diwako** [comment]
When saving/loading a save many global variables will be saved and set again. Have you tried to hide the UI and then show it again with the keybind? It might jump back to the position you wanted.

**Comment by aradiel** [comment]
Huh, I completely forgot about the keybinds when testing. That works perfectly, as soon as it starts up again it jumps back in the next frame or so.

**Comment by diwako** [comment]
👌
