### ISSUE TITLE
Feature - ACE3 Unit classes

### ISSUE THREAD

**Issue by nk3nny** [diwako/diwako_dui#32]
The support for ACE3 unit classes is awkward in certain scenarios.  We will sometimes set everyone to "ace_medical_medicClass" and "ace_isEngineer".  This is useful when portraying special forces or when circumventing gameplay limitations. 

In DUI this turns every icon into medic (or engineer) icons. Greatly lessening the utility of DUI.  Perhaps a CBA setting or custom variable could be added?

**Comment by diwako** [comment]
The order of icons on foot is
- Buddy
- SQL
- AR
- AT
- Medic
- Engineer
- Explosive Specialist
- Rifleman

So instead of everyone looking like a medic, everyone would look like a rifleman. In the end it would be the same, wouldn't it?

**Comment by Cyruz143** [comment]
Adjust your `ace_medical_medicSetting` per mission to lower the medic requirement rather than making everyone a medic. We had the same thing recently.

**Comment by nk3nny** [comment]
@Cyruz143, that is a pretty good fix for the medic situation! 

@diwako, perhaps you misunderstand. I like the icons and the order of selection. I am saying that it would be nice to be able to disable  ACE3 variable checking for roles like, engineer and medic.

**Comment by diwako** [comment]
Very one the fence on this. Tending towards no.

**Comment by diwako** [comment]
Closing this one as I have decided against it. That does not mean if someone makes a PR for it that I will straight up deny it.
