### ISSUE TITLE
Feature - Add setting for fade speed when unit outside occlusion cone.

### ISSUE THREAD

**Issue by Drofseh** [diwako/diwako_dui#38]
Like the title says, a setting for how many seconds it takes for a unit icon to fade away when that unit is outside the occlusion cone.

**Comment by diwako** [comment]
Just to get a feel for it, was 10 seconds too slow or too fast? In the end I will probably go with 2 to 30 seconds as a setting.

**Comment by Drofseh** [comment]
I'm not sure yet if I want it faster or slower for actual gameplay. 1 or 2 to 30 sounds fine to me.

I was making a comparison screenshot to show off the special tracking and kept having to spin around to make sure all the unit icons were visible, so for my screenshot purposes I wanted to set it longer.

**Comment by diwako** [comment]
I still consider this a feature request, but why not just disable occlusion for the screenshots? :V

**Comment by Drofseh** [comment]
Because I didn't think about that at the time. =D

**Comment by diwako** [comment]
Feature pushed into cba branch 9d864aaef00394043d5fa9da8df9d4263239f1bf
