### ISSUE TITLE
Bug - Error when object with no icon is added to tracking

### ISSUE THREAD

**Issue by Drofseh** [diwako/diwako_dui#40]
If a unit or object has no `icon` config entry and error pops up and no icon is displayed in the compass.

I noticed this when adding an object to special tracking that, it turned out, does not have an icon.

**Comment by Drofseh** [comment]
Solution would be to check if `icon` exists and if not default to another icon.

**Comment by diwako** [comment]
Possible to say which object that is? Just so I have one to test right away.

**Comment by Drofseh** [comment]
Yah, it was the Faces of War german halftack (Sd. KfZ 251)

**Comment by Drofseh** [comment]
Ok, it is that unit ^

Here's the actual error message I got.
https://i.gyazo.com/fbeafe58aee2b53e3fb1057553e44216.png

No icon is present in the hud. Maybe it's case sensitivity and not a missing icon like I assumed?

**Comment by Drofseh** [comment]
`fow_v_sdkfz_251_camo_ger_heer`
`icon = "iconTank";`

**Comment by diwako** [comment]
Of course it had to be a ww2 mod...

**Comment by Drofseh** [comment]
sorry, I pretty much only do WW2 arma these days.

**Comment by diwako** [comment]
I am having a bit of a gripe with ww2 mods, mostly because of stuff like this. I am not sure if there is even a way to detect if that entry of the configs is correct or not. I might be able to determine if the last few characters of the path are ".paa". But then there is still no guarantee and maybe even false positives.

**Comment by diwako** [comment]
![image](https://user-images.githubusercontent.com/8259498/52734255-01657580-2fc5-11e9-8ba4-4abf7c21fcc7.png)
there we go cb248efff13787e72bbb82d6ec7eb16e9e2c16b0

**Comment by Drofseh** [comment]
Nice
