### ISSUE TITLE
Feature - Use ACE nametag colors

### ISSUE THREAD

**Issue by synixebrett** [diwako/diwako_dui#42]
There is a color style for ACE, but it would be nice to actually pull the colors from ACE nametags if it is present. Only thing standing in the way right now is the use of hex colors, some minor rewriting would need to be done.

**Comment by diwako** [comment]
RGB to hex is already a requirement for another issue. Meaning that will be already covered. One thing I am not sure about is changing the colors in name tags and updating the cached colors in DUI's namespaces.

**Comment by synixebrett** [comment]
Should be able to use https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#setting-changed-script-_script to handle the settings being changed

**Comment by diwako** [comment]
Added with 2f7aa27be6bdc00d6d5dc578bb603f8a087982c0

**Comment by diwako** [comment]
Going to reopen this, as right now the nametag color support is its own selection besides the ACE3 option.

Wouldn't it be better to just merge that into the ACE3 option if nametags is present?

**Comment by diwako** [comment]
And closed again as i just implemented it like that, i think that is better
