### ISSUE TITLE
Feature – Hold-To-Show / Hide

### ISSUE THREAD

**Issue by Quailsnap** [diwako/diwako_dui#45]
First -- awesome, amazing, perfect script. Love it.
Could we get a setting that has the compass off by default, but shows it on button hold? There's already a "toggle" button that can be bound, but I'm interested in eventually having one button I can use to check my entire UI (think Rising Storm) and, other than that, the UI is entirely hidden.

If I get time next weekend I may very well just pull a feature like that myself. Trying to get my unit (COALITION) to implement this awesome radar over old, stale STHUD.

**Comment by diwako** [comment]
Question, with entire UI do you mean the whole of A3's ui or just DUI Elements?

**Comment by Quailsnap** [comment]
Just DUI elements. Various Arma HUD elements (pretty much all of them if you're infantry) can be hidden and will only show upon certain actions -- reloading, firemode changes, zeroing, grenade selection for weapon info, stamina use for the stamina bar, etc.

**Comment by diwako** [comment]
How would a solution sound in which you can hide DUI by default and you get an extra keybind which you need to hold.
That means if you show it by default and you hold the keybind, you will hide DUI until you let go, but if you hide it by default and you hold the keybind you show it until you let go?

**Comment by Quailsnap** [comment]
Exactly what I had in mind!

**Comment by diwako** [comment]
Commited with 7d7c0bde2a44436e1bb45b3d1e538b1d0c351cac

Also available on DEV workshop page for preview!
