### ISSUE TITLE
Feature Req - Row Width

### ISSUE THREAD

**Issue by tanaaKa** [diwako/diwako_dui#46]
I'm a big fan of six names in one column as a "clean" look. If I make text size as small as possible, I can fit, at most, five names to a column, but they're not very readable due to small size. If possible, will you add a way to ensure six names can be fit into one column like with adjustable row widths?

**Comment by Drofseh** [comment]
I've been thinking about this as well.
UI and text scaling effects the number of named per column, but sometimes means that there is extra space that goes unused.

My current settings could display more named but instead starts another column.
UI Size - 1.25
Text Size - 0.8
Column Width - 150
https://i.gyazo.com/c4f02d75092fd89044562b228f96d3d5.png

If there was a setting to force the number of names per column I think that would be nice.

**Comment by diwako** [comment]
I've completely rewritten how columns work in the namelist for 1.4.0. That change is currently live for preview on the Dev upload in steam
https://steamcommunity.com/sharedfiles/filedetails/?id=1617125729

In that preview, each Unit name is its own element and it will try to fill the complete height of the namelistbox before breaking into a second column. Additionally a row height modifier is added for people with larger resolutions. With that you can fiddle around until you get the desired results.

**Comment by tanaaKa** [comment]
Awesome! With this I'll be transitioning my community over to DUI from STUI. Thanks for your hard work!

**Comment by diwako** [comment]
Keep in mind 1.4.0 is currently not released. I am still waiting for some feedback before I push it to the main steam workshop item and tag it as release.

**Comment by Drofseh** [comment]
Nice! I just had a look at the dev version and it looks good to me.

**Comment by diwako** [comment]
So, both of you are happy with how it is in the current dev version?

**Comment by Drofseh** [comment]
I am

**Comment by tanaaKa** [comment]
Looks and works great to me.

**Comment by diwako** [comment]
Great, since 1.4.0 is now released I am also closing this.
