### ISSUE TITLE
Feature - Fov shown on compass

### ISSUE THREAD

**Issue by diwako** [diwako/diwako_dui#5]
Fov should be shown by 2 bars on compass.

https://cbateam.github.io/CBA_A3/docs/files/common/fnc_getFov-sqf.html

This could be used, needs benchmarking tho. the 2 bars should also have one texture which is mirrored between them.

**Comment by Scorch052** [comment]
Would this be a potential solution to this:
https://github.com/diwako/diwako_dui/issues/8

I play with a nonstandard FOV and encounter the same bug shown in the video.

**Comment by diwako** [comment]
Sadly there is no fix for warped images when running custom FOV. I already opened up a ticket for BI in the hopes that it might be fixed in the future:
https://feedback.bistudio.com/T136844

**Comment by SekiAlpha** [comment]
Just want to note that the STUI hud doesn't have this issue, at least as far as I can tell.

**Comment by diwako** [comment]
> Just want to note that the STUI hud doesn't have this issue, at least as far as I can tell.

Known, STUI does not use ctrlSetAngle.

**Comment by SekiAlpha** [comment]
Would it be difficult for you to use STUIs method because I don't think bohemia is fixing this issue any time soon?

**Comment by diwako** [comment]
> Would it be difficult for you to use STUIs method because I don't think bohemia is fixing this issue any time soon?

Using STUIs method would mean three things:

1. throwing away nearly all code regarding the radar
2. performance will be worse
3. several customization options will not be possible anymore
