### ISSUE TITLE
Issue - Mod Name may be Long

### ISSUE THREAD

**Issue by Quailsnap** [diwako/diwako_dui#51]
Traditionally Arma addon authors have kept their names condensed: ( "@ACE", "@CBA_A3", "@STUI" ) because the -mod parameter is constrained by a character limit. Many groups have to coalesce mods into their own "packs" (ie: coalition throws their maps into "@COALITION_MAPS" or something like that) to ensure they don't go over the character limit (or an unrelated but also-present mod limit).

There are alternatives that most places have started using now (steam workshop, running a .bat instead of a modified .exe, etc) that go around this limitation, but it's still present for many, and most mod authors still keep their @NAME very short as a consequence.

Perhaps @DUI_HUD?

**Comment by diwako** [comment]
If you are using the workshop release, it is tied to the workshop name. Cannot rename the folder on it self. If you use the github release you can just rename it.

Multiple -mod parameters are also possible.
