### ISSUE TITLE
Feature Req - Other Spectate Modes 

### ISSUE THREAD

**Issue by tanaaKa** [diwako/diwako_dui#52]
Currently, my community uses potato spectator, found here:
https://github.com/BourbonWarfare/POTATO/tree/master/addons/spectate

This is a rewritten version of ace spectator and doesn't use the ``ace_spectator_isSet`` variable that is detected in ``fnc_canHudBeShown.sqf``. 

The issue right now is that DUI hides itself when the player dies and then reinitializes when the player enters spectate. I wrote a quick hotfix that detects whether the player is in a spectator unit and hides the compass, but it doesn't hide the name list. If you find some time, I'd greatly appreciate this!

**Comment by diwako** [comment]
I never heard of that so far. Could you take a look what both of these variables are set to when you are spectating?
```sqf
potato_spectate_running
potato_spectate_respawnOpen
```

**Comment by diwako** [comment]
Actually, looking through your fork of DUI, maybe adding a check for acre/tfar spectator mode would be better. Covers more ground than just this spectator.

**Comment by tanaaKa** [comment]
For sure. That's where I went first and it didn't seem to get the job done at first. I'm sure that'd be much more dynamic though.

**Comment by diwako** [comment]
Variables to use:
ACRE_IS_SPECTATOR
_player getVariable ["TFAR_forceSpectator", false]

**Comment by diwako** [comment]
Added with 065baa18101f8416fb9f6893ac43e1dec85903cd

Also pushed to dev workshop item for preview.
