### ISSUE TITLE
Distance Calculation

### ISSUE THREAD

**Issue by synixebrett** [diwako/diwako_dui#55]
Not sure if this is intended or not but the radar is using `distance2d` instead of `distance` [here](https://github.com/diwako/diwako_dui/blob/d3b1766c930547af56563c15e01521f0046f11b2/addons/radar/functions/fnc_displayUnitOnCompass.sqf#L24). This means that a paratrooper 2km in the air above the player will appear on the radar.

**Comment by diwako** [comment]
`distance2d` is intended as it appeared faster than `distance`. Arma is not really a vertical game, thus 2d calculation is more than enough.

**Comment by synixebrett** [comment]
Sounds good, just wanted to make sure
