### ISSUE TITLE
Russian translations

### ISSUE THREAD

**Issue by topden** [diwako/diwako_dui#57]
https://drive.google.com/open?id=11_Cixlk09Vm-mT3iPBICR4B4QDEaAZzb

Hello) Thanks for the great mod and great work. I wish you success and wanted to make a small contribution for Russian-speaking players. Best wishes,
 [ATP] TopDen [ARMATOP]

**Comment by diwako** [comment]
Thanks you, added with commit fd820a42bdfc9bcb0f4979ead6e421444a304730

Pushed latest build to DEV workshop item for preview
