### ISSUE TITLE
Feature - Option for only showing bearings in vehicles

### ISSUE THREAD

**Issue by Cyruz143** [diwako/diwako_dui#6]
As per title, would be nice for minimal hud use on foot but with a bit more details in vehicle, as discussed on Slack.

**Comment by diwako** [comment]
Imo good feature request. I personally am a sucker for the bearing to always show, but I can understand people want it only in vehicles.

**Comment by diwako** [comment]
Option added with commit 05401ab4927ff36b55eba9d33518565e483bc482
