### ISSUE TITLE
Feature - Hide names when group leader

### ISSUE THREAD

**Issue by Freddo3000** [diwako/diwako_dui#64]
I'd like there to be an option for hiding names whenever you are the squad leader, as I prefer to have the vanilla group interface when I'm commanding as opposed to the DUI names list.

Minor thing, but hey.

**Comment by diwako** [comment]
Well that was easy enough to implement
969c22ee837142aa0d7e7460a61194324c5fb793

Pushed preview to DEV Workshop item for preview
