### ISSUE TITLE
Bug - Compass doesn't scale with higher resolutions

### ISSUE THREAD

**Issue by Cyruz143** [diwako/diwako_dui#7]
The compass is a fixed 128x128 element, at higher resolutions (examples screenshots @ 4k) the compass is very small and hard to read.

https://imgur.com/a/Bwz8Eco

As discussed in Slack might be worth getting the height of the resolution (getResolution) and scaling the element to 10% of the screen height for higher resolutions.

**Comment by diwako** [comment]
First batch of updates pushed with 16b35c313667a1d4a8d81e93233c3856371d7198

Compass icons size and bearing indicator are what is left to do.

**Comment by diwako** [comment]
With this commit ebb7e76e93067ea2b7df588c013bf569f3cc97ba icon scaling for the compass is now in. Just bearing left

**Comment by diwako** [comment]
With commit 2965bcb0a5a19d8442db1a9f3e3bfed0ff7dc334 now also bearing indicator scales. Issue should be resolved.

Tell me if something is amiss and i will reopen this issue.
