### ISSUE TITLE
Modularity

### ISSUE THREAD

**Issue by synixebrett** [diwako/diwako_dui#73]
It would be nice if diwako_dui had full modularity, where any combination components could be removed and the others would still work.

Right now `indicators` can be removed without a problem. `radar` can't because of a call in [indicators](https://github.com/diwako/diwako_dui/blob/master/addons/indicators/functions/fnc_cacheLoop.sqf#L20).

I think the buddy system should be move to `main` or `common` (or even `buddy` to allow the buddy system to be removed entirely from the mod?). Then from that point on everything should be kept fully modular.

**Comment by diwako** [comment]
I actually do not see why not. I'd go for its own module, so people can remove it if they truly do not want that feature.

**Comment by diwako** [comment]
Aaand done. d7df624bd57ed05119acb69289bb92ee9fbe65a9
