### ISSUE TITLE
Feature - Change indicator size based on distance (bonus: FoV?)

### ISSUE THREAD

**Issue by Quailsnap** [diwako/diwako_dui#77]
Little QoL change that could be as simple as 
"_size = ( GVAR(size) / (player distance target) ) max GVAR(min_size)"
Note that distance2D would not work for obvious reasons.

This would avoid nasty-looking scenarios in which the hexagons / circles / squares are larger than the unit they are rendered on.

Bonus: Modulate it by FoV, too, and have the indicators essentially scale as if they actually existed. Much prettier! (Ugly as hell) example code here:

https://github.com/Quailsnap/WHA-Nametags/blob/master/wha_nametags.Stratis/wha/nametags/functions/fn_drawUnit.sqf#L93

**Comment by diwako** [comment]
It is an idea I also had at some point, but wasn't sure to add it or not. I saw it as kind of the point of the indicators staying the same size as they are a visual aid. Making them smaller seemed counter intuitive for me (as it makes them harder to spot).

This is still a sound request. As far as I see it, it will add 2 more settings overall.
* Enable autosize (name alright?) (Checkbox, default off)
* Min autosize Indicator Size (Slider between 0 and max of size slider, also will only work if checkbox is active)

fov is a soso thing. I will look into that once I get some free time.

Would an implementation like that satisfy the request?

**Comment by Quailsnap** [comment]
Works for me! I don't use the indicators, but for those that do I imagine this may make things a little cleaner looking, especially so if FoV is included.

In the end it could be a dropdown -- A. Static size; B. Scale with FoV; C. Scale with distance; D. Scale with FoV and Distance.

**Comment by diwako** [comment]
![image](https://user-images.githubusercontent.com/8259498/55573112-7887d200-5709-11e9-8689-13ec515c4727.png)
Implemented it as this right now. Scaling with range and fov. Both are Checkboxes so you can do all 4 options you suggested.

![image](https://user-images.githubusercontent.com/8259498/55573203-bdac0400-5709-11e9-8884-f53cd0d51b86.png)
ignore my typo that I hid :V

**Comment by diwako** [comment]
Pushed onto DEV Workshop Item for preview. @Quailsnap tell me if that is alright like this.

**Comment by Quailsnap** [comment]
They're beautiful! I don't see any reason why they shouldn't be on by default, but that's up to you.
Hell – they're pretty enough that I might start using them.
