### ISSUE TITLE
Feature - Bearing number has leading zeroes

### ISSUE THREAD

**Issue by diwako** [diwako/diwako_dui#81]
059c66e55a5fb70b06c141115528c7556928269c

**Comment by Drofseh** [comment]
leading zeros seem good to me, I'd rather keep them

**Comment by Drofseh** [comment]
For example, 75 degrees should normally be read as Zero Seven Five when giving a bearing.

**Comment by diwako** [comment]
It is an option now ;) 

Just made this issue so it shows up on the milestone page

**Comment by Drofseh** [comment]
Sounds good
