### ISSUE TITLE
Radar Bearing > 360

### ISSUE THREAD

**Issue by nomisum** [diwako/diwako_dui#98]
In yesterdays game we had (sometimes) radar bearings up to 5999 instead of 360.

Might be GM related, as we used all the new equipment and compasses. Also iirc this might have been only when in vehicles.

If necessary I could investigate further.

**Comment by Fusselwurm** [comment]
intentional, see discussion in #94

**Comment by Fusselwurm** [comment]
:thinking: afaics, you could hack this by setting `GVAR(oddDirectionCompasses) = [];` :trollface:  to get the vanilla range of 0…360 regardless of compass type

**Comment by diwako** [comment]
Indeed intentional, the GM compasses all use mils. one goes up to 60k the other up to 64k. I wrote a small wiki page about the underlying "framework" of it. It can be changed at any time after preinit.

https://github.com/diwako/diwako_dui/wiki/Custom-compass-items-and-custom-ranges

**Comment by nomisum** [comment]
thanks for clarifying
